# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - abc-bank

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_7434f0faa9e34db5b50dad3a407339e8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c06b4d11d7a2469eb0f0c24ad3fc2a0c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7434f0faa9e34db5b50dad3a407339e8 }}/abc_bank:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'abc-bank'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1d4ed879a99745edac2c277eeff90850 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7434f0faa9e34db5b50dad3a407339e8 }}/abc_bank:${{ github.sha }}'