# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - abc-bank

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://abcbankregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d9bb31f4c22a41ada99fadfcb5d24e19 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_135e6e7dba674b918eabbd7f810e764b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: abcbankregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d9bb31f4c22a41ada99fadfcb5d24e19 }}/abc_bank:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'abc-bank'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d9828332d0b540cba4dcba1d50fb75d5 }}
        images: 'abcbankregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d9bb31f4c22a41ada99fadfcb5d24e19 }}/abc_bank:${{ github.sha }}'